const usStateAbbreviations = [
  { key: "Select State", value: "", combinedTax: undefined },
  { key: "AL", value: "AL", combinedTax: 0.04 },
  { key: "AK", value: "AK", combinedTax: 0 },
  { key: "AZ", value: "AZ", combinedTax: 0.056 },
  { key: "AR", value: "AR", combinedTax: 0.065 },
  { key: "CA", value: "CA", combinedTax: 0.0725 },
  { key: "CO", value: "CO", combinedTax: 0.029 },
  { key: "CT", value: "CT", combinedTax: 0.0635 },
  { key: "DE", value: "DE", combinedTax: 0 },
  { key: "FL", value: "FL", combinedTax: 0.06 },
  { key: "GA", value: "GA", combinedTax: 0.04 },
  { key: "HI", value: "HI", combinedTax: 0.04 },
  { key: "ID", value: "ID", combinedTax: 0.06 },
  { key: "IL", value: "IL", combinedTax: 0.0625 },
  { key: "IN", value: "IN", combinedTax: 0.07 },
  { key: "IA", value: "IA", combinedTax: 0.06 },
  { key: "KS", value: "KS", combinedTax: 0.065 },
  { key: "KY", value: "KY", combinedTax: 0.06 },
  { key: "LA", value: "LA", combinedTax: 0.0445 },
  { key: "ME", value: "ME", combinedTax: 0.055 },
  { key: "MD", value: "MD", combinedTax: 0.06 },
  { key: "MA", value: "MA", combinedTax: 0.0625 },
  { key: "MI", value: "MI", combinedTax: 0.06 },
  { key: "MN", value: "MN", combinedTax: 0.06875 },
  { key: "MS", value: "MS", combinedTax: 0.07 },
  { key: "MO", value: "MO", combinedTax: 0.04225 },
  { key: "MT", value: "MT", combinedTax: 0 },
  { key: "NE", value: "NE", combinedTax: 0.055 },
  { key: "NV", value: "NV", combinedTax: 0.0685 },
  { key: "NH", value: "NH", combinedTax: 0 },
  { key: "NJ", value: "NJ", combinedTax: 0.06625 },
  { key: "NM", value: "NM", combinedTax: 0.05125 },
  { key: "NY", value: "NY", combinedTax: 0.04 },
  { key: "NC", value: "NC", combinedTax: 0.0475 },
  { key: "ND", value: "ND", combinedTax: 0.05 },
  { key: "OH", value: "OH", combinedTax: 0.0575 },
  { key: "OK", value: "OK", combinedTax: 0.045 },
  { key: "OR", value: "OR", combinedTax: 0 },
  { key: "PA", value: "PA", combinedTax: 0.06 },
  { key: "RI", value: "RI", combinedTax: 0.07 },
  { key: "SC", value: "SC", combinedTax: 0.06 },
  { key: "SD", value: "SD", combinedTax: 0.045 },
  { key: "TN", value: "TN", combinedTax: 0.07 },
  { key: "TX", value: "TX", combinedTax: 0.0625 },
  { key: "UT", value: "UT", combinedTax: 0.0485 },
  { key: "VT", value: "VT", combinedTax: 0.06 },
  { key: "VA", value: "VA", combinedTax: 0.053 },
  { key: "WA", value: "WA", combinedTax: 0.065 },
  { key: "WV", value: "WV", combinedTax: 0.06 },
  { key: "WI", value: "WI", combinedTax: 0.05 },
  { key: "WY", value: "WY", combinedTax: 0.04 },
];

export default usStateAbbreviations;
